sudo: required
services:
  - docker

before_install:

  - docker build -t shiva6193/docker-react -f Dockerfile.dev .

script:

  - docker run shiva6193/docker-react npm run test -- --coverage


deploy:

  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name : "elasticbeanstalk-ap-south-1-592479170546"
  bucket_path: "Docker-React"
      
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"