version: "3.7"
services: 
  web:

    build: 
      context: .
      dockerfile: Dockerfile.dev

    ports: 
      - "3000:3000"

    volumes: 

      - /app/code/node_modules
      - .:/app/code

  tests:

    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes: 
      - /app/code/node_modules
      - .:/app/code
    command: ["npm", "run", "test"]
     
      

